//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Elias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instractor
    {
        public int InstractorID { get; set; }
        public string InstractorName { get; set; }
        public string EmailAddress { get; set; }
        public string CellPhone { get; set; }
        public string ContactAddress { get; set; }
    }
}
